const SESSION_COOKIE = "__Host-moon_session";
const SESSION_TTL = 60 * 60 * 24 * 30;
const MAX_MEDIA_BYTES = 15 * 1024 * 1024;
const MAX_TIMELINE_BYTES = 50 * 1024 * 1024;
const SEED_TIMELINE = [
  { id: "birth", title: "时光的起点", note: "时沐恩来到这个世界。", occurredAt: "2026-08-25T08:52:00+08:00", kind: "text", system: 1 },
  { id: "first-meeting", title: "初见", note: "出生后的第一张小小肖像。", occurredAt: "2026-08-25T11:29:00+08:00", kind: "image", assetUrl: "/assets/photos/first-meeting.jpg", system: 1 },
  { id: "day-six-dream", title: "第六天的梦", note: "睡得很安静的一天。", occurredAt: "2026-08-30T20:36:00+08:00", kind: "image", assetUrl: "/assets/photos/sleeping-day-six.jpg", system: 1 },
  { id: "day-eight-light", title: "第八天的晨光", note: "阳光落在小手和脸颊上。", occurredAt: "2026-09-01T10:51:00+08:00", kind: "image", assetUrl: "/assets/photos/morning-day-eight.jpg", system: 1 },
];

function json(data, status = 200, extraHeaders = {}) {
  return new Response(JSON.stringify(data), { status, headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store", ...extraHeaders } });
}
function base64Url(bytes) { return btoa(String.fromCharCode(...bytes)).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", ""); }
function fromBase64Url(value) { const padded = value.replaceAll("-", "+").replaceAll("_", "/") + "===".slice((value.length + 3) % 4); return Uint8Array.from(atob(padded), (char) => char.charCodeAt(0)); }
async function digest(value) { return new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value))); }
async function encryptionKey(env) {
  const secret = env.MOON_ENCRYPTION_KEY || env.MOON_INITIAL_PASSWORD;
  if (!secret) throw new Error("MOON_ENCRYPTION_KEY is not configured");
  return crypto.subtle.importKey("raw", await digest(secret), { name: "AES-GCM" }, false, ["encrypt", "decrypt"]);
}
async function encrypt(value, env) { const iv = crypto.getRandomValues(new Uint8Array(12)); const encrypted = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, await encryptionKey(env), new TextEncoder().encode(value)); return `${base64Url(iv)}.${base64Url(new Uint8Array(encrypted))}`; }
async function decrypt(value, env) { const [ivText, cipherText] = String(value || "").split("."); if (!ivText || !cipherText) throw new Error("Invalid encrypted value"); const plain = await crypto.subtle.decrypt({ name: "AES-GCM", iv: fromBase64Url(ivText) }, await encryptionKey(env), fromBase64Url(cipherText)); return new TextDecoder().decode(plain); }
async function safeEqual(left, right) { const a = await digest(left); const b = await digest(right); let result = a.length === b.length ? 0 : 1; for (let index = 0; index < Math.max(a.length, b.length); index += 1) result |= (a[index] || 0) ^ (b[index] || 0); return result === 0; }
function cookieValue(request) { const cookies = request.headers.get("cookie") || ""; const found = cookies.split(";").map((part) => part.trim()).find((part) => part.startsWith(`${SESSION_COOKIE}=`)); return found ? found.slice(SESSION_COOKIE.length + 1) : ""; }
async function sign(value, env) { const key = await crypto.subtle.importKey("raw", await digest(env.MOON_SESSION_SECRET || env.MOON_ENCRYPTION_KEY || env.MOON_INITIAL_PASSWORD || "moon"), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); return base64Url(new Uint8Array(await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(value)))); }
async function issueSession(version, env, role = "viewer") { const payload = { exp: Math.floor(Date.now() / 1000) + SESSION_TTL, version, role, nonce: base64Url(crypto.getRandomValues(new Uint8Array(12))) }; const encoded = base64Url(new TextEncoder().encode(JSON.stringify(payload))); return `${encoded}.${await sign(encoded, env)}`; }
async function sessionFromRequest(request, env, db) { const token = cookieValue(request); if (!token) return null; const [encoded, signature] = token.split("."); if (!encoded || !signature || !(await safeEqual(signature, await sign(encoded, env)))) return null; try { const payload = JSON.parse(new TextDecoder().decode(fromBase64Url(encoded))); if (!payload.exp || payload.exp < Math.floor(Date.now() / 1000)) return null; const role = payload.role === "admin" ? "admin" : "viewer"; const versionKey = role === "admin" ? "admin_password_version" : "password_version"; const currentVersion = Number(await configValue(db, versionKey) || 0); if (currentVersion && Number(payload.version) !== currentVersion) return null; return { ...payload, role }; } catch { return null; } }

async function ensureSchema(db) {
  await db.batch([
    db.prepare("CREATE TABLE IF NOT EXISTS site_config (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TEXT NOT NULL)"),
    db.prepare("CREATE TABLE IF NOT EXISTS timeline_items (id TEXT PRIMARY KEY, title TEXT NOT NULL, note TEXT NOT NULL DEFAULT '', occurred_at TEXT NOT NULL, kind TEXT NOT NULL, asset_key TEXT, asset_url TEXT, file_name TEXT, mime_type TEXT, system INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL)"),
    db.prepare("CREATE TABLE IF NOT EXISTS blessings (id TEXT PRIMARY KEY, name TEXT NOT NULL, message TEXT NOT NULL DEFAULT '', audio_key TEXT, created_at TEXT NOT NULL, ip_hash TEXT)"),
    db.prepare("CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, event TEXT NOT NULL, ip_hash TEXT, user_agent_hash TEXT, created_at TEXT NOT NULL, metadata TEXT NOT NULL DEFAULT '{}')"),
    db.prepare("CREATE TABLE IF NOT EXISTS rate_limits (key TEXT PRIMARY KEY, count INTEGER NOT NULL, window_start INTEGER NOT NULL)"),
  ]);
}
async function configValue(db, key) { const row = await db.prepare("SELECT value FROM site_config WHERE key = ?1").bind(key).first(); return row?.value ?? null; }
async function setConfig(db, key, value) { await db.prepare("INSERT INTO site_config (key, value, updated_at) VALUES (?1, ?2, ?3) ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at").bind(key, value, new Date().toISOString()).run(); }
function clientIp(request) { return request.headers.get("CF-Connecting-IP") || request.headers.get("X-Forwarded-For")?.split(",")[0]?.trim() || "unknown"; }
async function audit(db, request, event, metadata = {}) { const [ipHash, uaHash] = await Promise.all([digest(clientIp(request)), digest(request.headers.get("user-agent") || "unknown")]); await db.prepare("INSERT INTO audit_logs (event, ip_hash, user_agent_hash, created_at, metadata) VALUES (?1, ?2, ?3, ?4, ?5)").bind(event, base64Url(ipHash), base64Url(uaHash), new Date().toISOString(), JSON.stringify(metadata)).run(); }
async function rateLimit(db, request) { const now = Math.floor(Date.now() / 1000); const windowStart = now - (now % 900); const key = base64Url(await digest(`${clientIp(request)}:${windowStart}`)); const row = await db.prepare("SELECT count, window_start FROM rate_limits WHERE key = ?1").bind(key).first(); if (row && Number(row.window_start) === windowStart && Number(row.count) >= 8) return false; await db.prepare("INSERT INTO rate_limits (key, count, window_start) VALUES (?1, 1, ?2) ON CONFLICT(key) DO UPDATE SET count = CASE WHEN rate_limits.window_start = excluded.window_start THEN rate_limits.count + 1 ELSE 1 END, window_start = excluded.window_start").bind(key, windowStart).run(); return true; }
async function seedTimeline(db) { const row = await db.prepare("SELECT COUNT(*) AS count FROM timeline_items").first(); if (Number(row?.count || 0) > 0) return; const now = new Date().toISOString(); await db.batch(SEED_TIMELINE.map((item) => db.prepare("INSERT OR IGNORE INTO timeline_items (id, title, note, occurred_at, kind, asset_key, asset_url, file_name, mime_type, system, created_at) VALUES (?1, ?2, ?3, ?4, ?5, NULL, ?6, '', '', ?7, ?8)").bind(item.id, item.title, item.note, item.occurredAt, item.kind, item.assetUrl || null, item.system, now))); }
async function ensurePassword(db, env) { let cipher = await configValue(db, "password_ciphertext"); let version = Number(await configValue(db, "password_version") || 0); if (!cipher) { if (!env.MOON_INITIAL_PASSWORD) throw new Error("MOON_INITIAL_PASSWORD is not configured"); cipher = await encrypt(env.MOON_INITIAL_PASSWORD, env); version = 1; await setConfig(db, "password_ciphertext", cipher); await setConfig(db, "password_version", String(version)); await setConfig(db, "password_updated_at", new Date().toISOString()); } return { cipher, version }; }
async function ensureAdminPassword(db, env) { let cipher = await configValue(db, "admin_password_ciphertext"); let version = Number(await configValue(db, "admin_password_version") || 0); if (!cipher) { if (!env.MOON_ADMIN_PASSWORD) throw new Error("MOON_ADMIN_PASSWORD is not configured"); cipher = await encrypt(env.MOON_ADMIN_PASSWORD, env); version = 1; await setConfig(db, "admin_password_ciphertext", cipher); await setConfig(db, "admin_password_version", String(version)); await setConfig(db, "admin_password_updated_at", new Date().toISOString()); } return { cipher, version }; }
async function rotatePassword(db, env, request = null) { const current = await ensurePassword(db, env); const password = base64Url(crypto.getRandomValues(new Uint8Array(12))).slice(0, 16); await setConfig(db, "password_ciphertext", await encrypt(password, env)); await setConfig(db, "password_version", String(current.version + 1)); await setConfig(db, "password_updated_at", new Date().toISOString()); if (request) await audit(db, request, "password_rotated", { version: current.version + 1 }); return { password, version: current.version + 1 }; }
async function rotatePasswordIfDue(db, env, scheduledTime = Date.now()) { const configured = await ensurePassword(db, env); await ensureAdminPassword(db, env); const updatedAt = await configValue(db, "password_updated_at"); if (!updatedAt) return { rotated: false, version: configured.version }; const scheduleDate = new Date(scheduledTime); const previousDate = new Date(updatedAt); const sameMonth = previousDate.getUTCFullYear() === scheduleDate.getUTCFullYear() && previousDate.getUTCMonth() === scheduleDate.getUTCMonth(); if (sameMonth) return { rotated: false, version: configured.version }; const rotated = await rotatePassword(db, env); return { rotated: true, version: rotated.version }; }
async function requireSession(request, env, db, requiredRole = "viewer") { const session = await sessionFromRequest(request, env, db); if (!session) return json({ error: "需要访问密码" }, 401); if (requiredRole === "admin" && session.role !== "admin") return json({ error: "需要管理员权限" }, 403); return null; }
function securityHeaders(response) { const headers = new Headers(response.headers); headers.set("x-content-type-options", "nosniff"); headers.set("x-frame-options", "DENY"); headers.set("referrer-policy", "no-referrer"); headers.set("permissions-policy", "microphone=(self), camera=(), geolocation=()"); headers.set("content-security-policy", "default-src 'self'; img-src 'self' data: blob:; media-src 'self' blob:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"); return new Response(response.body, { status: response.status, statusText: response.statusText, headers }); }

async function api(request, env, db) {
  await ensureSchema(db); await seedTimeline(db); const url = new URL(request.url); const path = url.pathname;
  if (path === "/api/auth/login" && request.method === "POST") { if (!(await rateLimit(db, request))) return json({ error: "尝试次数过多，请稍后再试。" }, 429, { "retry-after": "900" }); if (Number(request.headers.get("content-length") || 0) > 2048) return json({ error: "请求无效。" }, 400); const body = await request.json().catch(() => ({})); const password = String(body.password || ""); const role = body.role === "admin" ? "admin" : "viewer"; const configured = role === "admin" ? await ensureAdminPassword(db, env) : await ensurePassword(db, env); const expected = await decrypt(configured.cipher, env); if (!password || !(await safeEqual(password, expected))) { await audit(db, request, role === "admin" ? "admin_login_failed" : "login_failed"); return json({ error: "密码不正确。" }, 401); } const token = await issueSession(configured.version, env, role); await audit(db, request, role === "admin" ? "admin_login_succeeded" : "login_succeeded"); return json({ ok: true, role }, 200, { "set-cookie": `${SESSION_COOKIE}=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${SESSION_TTL}` }); }
  if (path === "/api/auth/logout" && request.method === "POST") { await audit(db, request, "logout"); return json({ ok: true }, 200, { "set-cookie": `${SESSION_COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0` }); }
  if (path === "/api/session" && request.method === "GET") { const session = await sessionFromRequest(request, env, db); return json({ authenticated: Boolean(session), expiresAt: session?.exp ? new Date(session.exp * 1000).toISOString() : null }, session ? 200 : 401); }
  if (path === "/api/state" && request.method === "GET") { const denied = await requireSession(request, env, db); if (denied) return denied; const [timelineRows, blessingRows] = await Promise.all([db.prepare("SELECT id, title, note, occurred_at AS occurredAt, kind, asset_key AS assetKey, asset_url AS assetUrl, file_name AS fileName, mime_type AS mimeType, system FROM timeline_items ORDER BY occurred_at ASC").all(), db.prepare("SELECT id, name, message, audio_key AS audioKey, created_at AS createdAt FROM blessings ORDER BY created_at DESC").all()]); await audit(db, request, "state_viewed"); return json({ timeline: timelineRows.results || [], blessings: blessingRows.results || [] }); }
  const denied = await requireSession(request, env, db); if (denied) return denied;
  if (path === "/api/blessings" && request.method === "POST") { if (Number(request.headers.get("content-length") || 0) > 12000) return json({ error: "祝福内容太长了。" }, 413); const body = await request.json().catch(() => ({})); const id = String(body.id || crypto.randomUUID()).slice(0, 80); const name = String(body.name || "").trim().slice(0, 80); const message = String(body.message || "").trim().slice(0, 1000); const audioKey = body.audioKey ? String(body.audioKey).slice(0, 180) : null; if (!name || (!message && !audioKey)) return json({ error: "称呼与祝福内容不能为空。" }, 400); await db.prepare("INSERT INTO blessings (id, name, message, audio_key, created_at, ip_hash) VALUES (?1, ?2, ?3, ?4, ?5, ?6)").bind(id, name, message, audioKey, new Date().toISOString(), base64Url(await digest(clientIp(request)))).run(); await audit(db, request, "blessing_created", { id }); return json({ ok: true, id }); }
  if (path === "/api/media" && request.method === "POST") { if (!env.MEDIA) return json({ error: "媒体存储尚未配置。" }, 503); const length = Number(request.headers.get("content-length") || 0); if (length > MAX_MEDIA_BYTES) return json({ error: "声音文件不能超过 15MB。" }, 413); const form = await request.formData(); const file = form.get("file"); if (!(file instanceof File) || !file.size || !file.type.startsWith("audio/")) return json({ error: "请上传音频文件。" }, 400); if (file.size > MAX_MEDIA_BYTES) return json({ error: "声音文件不能超过 15MB。" }, 413); const key = `blessings/${crypto.randomUUID()}`; await env.MEDIA.put(key, file.stream(), { httpMetadata: { contentType: file.type, cacheControl: "private, no-store" } }); await audit(db, request, "audio_uploaded", { key }); return json({ key }); }
  if (path.startsWith("/api/media/") && request.method === "GET") { if (!env.MEDIA) return new Response("Media storage is not configured", { status: 503 }); const key = decodeURIComponent(path.slice("/api/media/".length)); if (!/^blessings\/[a-z0-9-]+$/i.test(key) && !/^timeline\/[a-z0-9-]+\.[a-z0-9]+$/i.test(key)) return new Response("Not found", { status: 404 }); const object = await env.MEDIA.get(key); if (!object) return new Response("Not found", { status: 404 }); await audit(db, request, "media_viewed", { key }); const headers = new Headers(); object.writeHttpMetadata(headers); headers.set("cache-control", "private, no-store"); return new Response(object.body, { headers }); }
  if (path === "/api/admin/current-password" && request.method === "GET") { const adminDenied = await requireSession(request, env, db, "admin"); if (adminDenied) return adminDenied; const configured = await ensurePassword(db, env); await audit(db, request, "password_viewed"); return json({ password: await decrypt(configured.cipher, env), updatedAt: await configValue(db, "password_updated_at"), version: configured.version }); }
  if (path === "/api/admin/timeline" && request.method === "POST") { const adminDenied = await requireSession(request, env, db, "admin"); if (adminDenied) return adminDenied; const length = Number(request.headers.get("content-length") || 0); if (length > MAX_TIMELINE_BYTES) return json({ error: "单条记录不能超过 50MB。" }, 413); const form = await request.formData(); const id = String(form.get("id") || crypto.randomUUID()).slice(0, 80); const title = String(form.get("title") || "").trim().slice(0, 120); const note = String(form.get("note") || "").trim().slice(0, 1000); const dateText = String(form.get("occurredAt") || ""); const occurredAt = new Date(dateText); const file = form.get("attachment"); if (!title || Number.isNaN(occurredAt.getTime())) return json({ error: "标题和时间不能为空。" }, 400); let assetKey = null; let fileName = ""; let mimeType = ""; let kind = "text"; if (file instanceof File && file.size) { if (file.size > MAX_TIMELINE_BYTES || !env.MEDIA) return json({ error: "媒体存储尚未配置或文件过大。" }, 503); assetKey = `timeline/${id}-${crypto.randomUUID()}`; fileName = file.name.slice(0, 200); mimeType = file.type || "application/octet-stream"; kind = mimeType.startsWith("image/") ? "image" : mimeType.startsWith("audio/") ? "audio" : mimeType.startsWith("video/") ? "video" : "document"; await env.MEDIA.put(assetKey, file.stream(), { httpMetadata: { contentType: mimeType, cacheControl: "private, no-store" } }); } await db.prepare("INSERT OR REPLACE INTO timeline_items (id, title, note, occurred_at, kind, asset_key, asset_url, file_name, mime_type, system, created_at) VALUES (?1, ?2, ?3, ?4, ?5, ?6, NULL, ?7, ?8, 0, ?9)").bind(id, title, note, occurredAt.toISOString(), kind, assetKey, fileName, mimeType, new Date().toISOString()).run(); await audit(db, request, "timeline_created", { id }); return json({ ok: true, id }); }
  if (path.startsWith("/api/admin/timeline/") && request.method === "DELETE") { const adminDenied = await requireSession(request, env, db, "admin"); if (adminDenied) return adminDenied; const id = decodeURIComponent(path.slice("/api/admin/timeline/".length)); const row = await db.prepare("SELECT asset_key AS assetKey, system FROM timeline_items WHERE id = ?1").bind(id).first(); if (!row) return json({ error: "记录不存在。" }, 404); if (Number(row.system)) return json({ error: "出生记录不能删除。" }, 400); if (row.assetKey && env.MEDIA) await env.MEDIA.delete(row.assetKey); await db.prepare("DELETE FROM timeline_items WHERE id = ?1").bind(id).run(); await audit(db, request, "timeline_deleted", { id }); return json({ ok: true }); }
  if (path.startsWith("/api/admin/blessings/") && request.method === "DELETE") { const adminDenied = await requireSession(request, env, db, "admin"); if (adminDenied) return adminDenied; const id = decodeURIComponent(path.slice("/api/admin/blessings/".length)); const row = await db.prepare("SELECT audio_key AS audioKey FROM blessings WHERE id = ?1").bind(id).first(); if (!row) return json({ error: "祝福不存在。" }, 404); if (row.audioKey && env.MEDIA) await env.MEDIA.delete(row.audioKey); await db.prepare("DELETE FROM blessings WHERE id = ?1").bind(id).run(); await audit(db, request, "blessing_deleted", { id }); return json({ ok: true }); }
  return json({ error: "Not found" }, 404);
}

async function serve(request, env) { const path = new URL(request.url).pathname; if (env.DB && path.startsWith("/api/")) { try { return securityHeaders(await api(request, env, env.DB)); } catch (error) { console.error("moon_api_error", error?.message || error); return json({ error: "服务暂时不可用。" }, 500); } } if (env.DB && path.startsWith("/assets/photos/")) { try { await ensureSchema(env.DB); if (await requireSession(request, env, env.DB)) return securityHeaders(json({ error: "需要访问密码" }, 401)); } catch (error) { console.error("moon_asset_error", error?.message || error); return json({ error: "服务暂时不可用。" }, 503); } } const response = await env.ASSETS.fetch(request); const acceptsHtml = request.headers.get("accept")?.includes("text/html"); if (response.status !== 404 || !acceptsHtml || !["GET", "HEAD"].includes(request.method)) return securityHeaders(response); const indexUrl = new URL(request.url); indexUrl.pathname = "/index.html"; indexUrl.search = ""; return securityHeaders(await env.ASSETS.fetch(new Request(indexUrl, request))); }
export { api, ensureSchema, requireSession, rotatePasswordIfDue, securityHeaders };

export default { fetch: serve, async scheduled(controller, env) { if (!env.DB) return; await ensureSchema(env.DB); await seedTimeline(env.DB); const result = await rotatePasswordIfDue(env.DB, env, controller?.scheduledTime || Date.now()); if (result.rotated) console.log("moon_password_rotated", new Date(controller?.scheduledTime || Date.now()).toISOString().slice(0, 10)); } };
